modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_unrestricted_fluid_tank"
version="${version}"
displayName="Create: Unrestricted Fluid Tank"
authors="Aether_254"
description='''Makes Create Fluid Tank dimensions configurable and adds optional horizontal tanks.'''

[[mixins]]
config="create_unrestricted_fluid_tank.mixins.json"

[[dependencies.create_unrestricted_fluid_tank]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_unrestricted_fluid_tank]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_unrestricted_fluid_tank]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_unrestricted_fluid_tank]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"
